apiVersion: v1
kind: ConfigMap
metadata:
  name: NodeJs-app
  namespace: NodeJs-app-dev
  labels:
    app: NodeJs-app
    costcenter: aidevops
data:
  APP_ENV: production
  LOG_LEVEL: info
  API_URL: https://api.example.com
---
