apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejsapp
  namespace: nodejsapp-pt
  labels:
    app: nodejsapp
    costcenter: dvsaidevops
data:
  APP_ENV: production
  LOG_LEVEL: info
  API_URL: https://api.example.com
---
